### ISSUE TITLE
Revisiting deliverables

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-charter#27]
From Dom: 

Shouldn't we also revisit the language about the specific deliverables?
> QUIC in WebRTC
>    An extension to the WebRTC 1.0 API to enable use of peer-to-peer QUIC streams for data exchange.

**Comment by alvestrand** [comment]
Suggesting something like:
"Investigate whether the WebRTC 1.0 API needs to be extended in order to accomodate a choice of protocols supporting the data channel, or whether adding a new API surface to support other protocols such as QUIC is a better approach".
Might be enough to get SDP discussed seriously again :-)
