### ISSUE TITLE
Balance of new/extension work

### ISSUE THREAD

**Issue by michaelchampion** [w3c/webrtc-charter#44]
In the current charter, it is not clear what work items represent extensions to the 1.0 specification versus work on an entirely new "2.0" API.  Is the intent to pursue "2.0" as a monolithic
specification, or will the work be broken up into a series of specifications?  Will some of those specifications also represent extensions to 1.0?  The overall work plan is not clear.

**Comment by alvestrand** [comment]
My personal thinking is that the first phase will have to be a series of extensions as we explore the "2.0" space - since 1.0 is what there is to make extensions on, these will have to be 1.0 extensions.
Whether we fold them back into a monolithic "2.0" - or perhaps split the spec up in a different way - is not clear to me at this juncture.
