### ISSUE TITLE
Non-implemented feature removal

### ISSUE THREAD

**Issue by michaelchampion** [w3c/webrtc-charter#45]
The WPT test dashboard (see: https://wpt.fyi/webrtc ) shows a great many features of the 1.0 specification have only been implemented by a single browser or even no browsers.  This charter needs to outline a plan to remove features not meeting the interoperability requirements so that WebRTC 1.0 can finally get to Recommendation during the charter period.

**Comment by jeffjaffe** [comment]
@michaelchampion I agree that we need to focus on getting to REC.

Are you looking for:

a. A removal of features at this time, before we re-charter? 
b. A mere mention in the charter that Chairs will remove features that are not implemented?
c. The definition of a crisp process in the charter whereby the Chairs drive to remove those features by a certain milestone date in the charter?

**Comment by alvestrand** [comment]
This dashboard is at the moment a bit better at showing failing tests than it is at showing unimplemented features; by my count the lack of transceivers in Chrome is blocking 20-odd tests from turning green.

Still, there are things that should seriously be considered for removal; I believe such removal is within the current charter.

**Comment by michaelchampion** [comment]
@jeffjaffe something like b) or c) in your list -- a clear statement in the charter that the priority is to get to Rec on whatever timeline is in the charter, and that unimplemented features will be dropped / deferred when it is clear that leaving them in would force an extension.

**Comment by aboba** [comment]
@alvestrand  The WebRTC WPT tests have a false negative problem since tests of implemented features are failing due to dependencies on unimplemented features.  As a result, the dashboard is not currently a useful indication of what features are implemented.  To get that indication we will either need to fix the WPT false negative problem, or find another way to determine the [implemented feature set.](https://docs.google.com/document/d/1ZX_d2sZvRCkAQKIr4ZMNlGIMNJjVHuHFJK1gcZqp2-s/edit?ts=5abcf56a#)

Looking at the feature set not yet implemented by 2 browsers, it would appear that there are some unimplemented features which are droppable and others that might be separated out into a separate specification.  However, there are some features still being implemented (e.g. addTransceiver) that can't be removed without requiring major rework.
